version: "3.8"

volumes:
  db_data:
  app_gem_cache:

services:
  db:
    image: mysql:8.0.32
    container_name: sprint_suite_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  web:
    depends_on:
      - db
    build: .
    container_name: sprint_suite_web
    volumes:
      - .:/app
      - app_gem_cache:/gems
    # env_file:
    #   - .env.development.local
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=mysql2://root:password@db/sprint_suite_development
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
